
<?php
echo'

<p>
<div class="site-inner"><div class="content-sidebar-wrap"><main class="content"><article class="post-1814 post type-post status-publish format-standard has-post-thumbnail category-animal category-top-10 tag-snake entry" itemscope itemtype="http://schema.org/CreativeWork"><header class="entry-header"><h1 class="entry-title" itemprop="headline">दुनिया के 10 सबसे विषैले सांप (Top 10 Most Venomous Snake Of World)</h1></header><div class="entry-content" itemprop="text">


<p class="no-break"><span st_url="http://www.ajabgjab.com/2014/05/top-10-most-venomous-snake-of-world.html" st_title="दुनिया के 10 सबसे विषैले सांप (Top 10 Most Venomous Snake Of World)" class="st_fblike_hcount"></span>
<span st_url="http://www.ajabgjab.com/2014/05/top-10-most-venomous-snake-of-world.html" st_title="दुनिया के 10 सबसे विषैले सांप (Top 10 Most Venomous Snake Of World)" class="st_plusone_hcount"></span>
<span st_url="http://www.ajabgjab.com/2014/05/top-10-most-venomous-snake-of-world.html" st_title="दुनिया के 10 सबसे विषैले सांप (Top 10 Most Venomous Snake Of World)" class="st_sharethis_hcount"></span></p><div dir="ltr" style="text-align: left;"><strong>Top 10 Most Venomous Snake Information in Hindi</strong> :  आज हम आपको दुनिया में पाये जाने वाले 10 सबसे विषैले सांपो के बारे में बताएंगे। संसार में सांपो की 2500 से अधिक प्रजातिया पाई जाती है जिसमें से 500 के करीब ज़हरीली होती है।  हमने इन्ही में से 10 प्रजातियों का चयन किया है। हालांकि इनको किसी क्रम में रखना बहुत मुश्किल है क्योकि कई प्रजातियों  का ज़हर बहुत घातक है पर वो इंसानो को ज्यादा नुकसान नहीं पहुंचाते है जबकि कई प्रजातियों का ज़हर इतना घातक नहीं होता है फिर भी वो अपनी आक्रमकता से इंसानो को बहुत ज्यादा नुकसान पहुंचाते है।
<h5>1. समुद्री सांप (Belcher\'s Sea Snake) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://4.bp.blogspot.com/-nyelmEnP764/U3h0J5Kg8vI/AAAAAAAAIc0/T9DoVWMVaIE/s1600/belcher-sea-snake.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://4.bp.blogspot.com/-nyelmEnP764/U3h0J5Kg8vI/AAAAAAAAIc0/T9DoVWMVaIE/s1600/belcher-sea-snake.jpg" alt="Belcher\'s Sea Snake " width="400" height="196" border="0"></a></td>
</tr><tr>
</tr></tbody></table><div>सी स्नेक साउथ ईस्ट एशिया और नॉर्थन ऑस्ट्रेलिया में पाया जाता है।  यह सांप इस संसार का सबसे ज़हरीला सांप है।  इसके ज़हर की कुछ मिलीग्राम बुँदे ही 1000 इंसानो की मौत के लिए पर्याप्त है। हालांकि समुद्र में पाये जाने के कारण यह इंसानो के लिए इतना खतरनाक नहीं है। केवल मछुआरे ही मछली पकड़ते वक़्त कभी कभार इसका शिकार होते है। यह अधिकतर मौको पर इंसानो को काटने से बचता है बहुत ही रेयर केस में हि यह इंसान को काटता है।</div>
<div></div>
<h5>2. इंनलैंड ताइपन  (Inland Taipan) :</h5>
<div>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto; text-align: center;" href="http://3.bp.blogspot.com/-da4-xlQ1cIU/U3h0bf4mY_I/AAAAAAAAIdQ/5sn2jwWbMY4/s1600/inland-taipan.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://3.bp.blogspot.com/-da4-xlQ1cIU/U3h0bf4mY_I/AAAAAAAAIdQ/5sn2jwWbMY4/s1600/inland-taipan.jpg" alt="Inland Taipan" width="400" height="276" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>यह सांप जमीन पर पाये जाने वाले सांपो में सबसे ज़हरीला है।  इसकी एक बाईट में  100 मिलीग्राम तक ज़हर होता है जो की बहुत ज्यादा नहीं है पर यह इतना घातक होता है कि 100 इंसानो को मौत कि नींद सुला सकता है। इनका ज़हर रैटल स्नेक की तुलना में 10 गुना और कोबरा की तुलना में 50 गुना ज्यादा घातक होता है। यह सांप आबादी से दूर रहना पसंद करता है इसलिए इंसानो से इसका आमना सामना बहुत कम होता है और यदि हो भी जाए तो ये वहाँ से बच निकलने की कोशिश करता है। आपको यह जान के आशचर्य होगा की इस सांप के द्वारा इंसानो को काटने का कोई मामला आज तक रिकॉर्ड नहीं हुआ है। इसलिए इसे संत सांप की भी उपाधि दी जाती है।</p>
<h5>3. इस्टर्न ब्राउन स्नेक (Eastern Brown Snake) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://3.bp.blogspot.com/-1aCNDoco7GI/U3h0aWdbfJI/AAAAAAAAIdE/F-XH0uXLfdI/s1600/eastern-brown-snake-.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://3.bp.blogspot.com/-1aCNDoco7GI/U3h0aWdbfJI/AAAAAAAAIdE/F-XH0uXLfdI/s1600/eastern-brown-snake-.jpg" alt="Eastern Brown Snake " width="400" height="196" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>आस्ट्रेलिया में पाया जानेवाले यह  सांप  बहुत ही ज़हरीला होता है। इसका अंदाजा आप इसी बात से लगा सकते है की इसके ज़हर का 14,000 वां हिस्सा ही किसी इंसान को खत्म करने के लिए काफी है। उससे भी खराब बात यह है यह ऑस्ट्रेलिया में इंसानी इलाको के पास ज्यादा पाया जाता है। इस सांप का एक छोटा सा बच्चा भी किसी इंसान को मौत के घाट उतार सकता है।</p>
<p>इनकी चाल बेहद तेज होती है और एक बार खतरा महसूस होने पर ये पीछा करके काटते हैं। इसके काटने के बाद आंखों के आगे अंधेरा छाना, बहुत तेज़ दर्द, बहुत ज्यादा खून का बहना जैसी शिकायतें मरीज करता है। काटने के 5 मिनट के भीतर इंसान खत्म हो जाता है। यह सांप केवल मूवमेंट पर ही प्रतिक्रिया करता है इसलिए कभी इस सांप से आपका सामना हो तो बिलकुल स्थिर रहना  ही सबसे बढ़िया उपाय है।</p>
</div>
<h5>4. रैटलस्नेक (Rattle Snake) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="text-align: center;"><a style="clear: left; display: inline !important; margin-bottom: 1em; margin-left: auto; margin-right: auto; text-align: center;" href="http://3.bp.blogspot.com/-0oI_KdhCo0Y/U3h0cZ-Hy-I/AAAAAAAAIdk/JfBVUD-pdaw/s1600/rattlesnake.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://3.bp.blogspot.com/-0oI_KdhCo0Y/U3h0cZ-Hy-I/AAAAAAAAIdk/JfBVUD-pdaw/s1600/rattlesnake.jpg" alt="Rattle Snake" width="400" height="278" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>यह उत्तरी अमेरिका का सबसे ज़हरीला सांप है। यह सांप अपनी  पुंछ के आखरी सिरे पर बने छल्लों के कारण आसानी से पहचाना जाता है।  जब यह अपनी पुंछ को हिलाता है तो यह छल्ले, झुनझुने की तरह आवाज़ करते है इसलिए इसका नाम रैटलस्नेक पड़ा है। यह सांप अपनी कुल लम्बाई के 2/3 हिस्से तक वार सकता है जो की बहुत ज्यादा है। ये सांप बहुत ही गुस्सैला होता है।  इस सांप की सबसे बड़ी विशेषता यह है की इनके बच्चे, बड़ो से ज्यादा खतरनाक होते है। क्योकि बच्चो में बड़ो से ज्यादा ज़हर होता है।  बड़े होने के साथ ज़हर कम होता जाता है। इसके शरीर में हेमोटोक्सिक ज़हर पाया जाता है।  इस ज़हर के प्रभाव से ह्यूमन टिश्यू खत्म होने लगते हैं, ब्लड क्लॉटिंग बंद हो जाती है। इसके काटने के बाद 10 -15 मिनीट के अंदर एन्टीडोट दे दी जाए तो बचने के कुछ चांस हो सकते है अन्यथा मौत निश्चित है।</p>
<h5>5. डेथ एडर (Death Adder) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://4.bp.blogspot.com/-hJiY55eJhGE/U3h0aXG4wtI/AAAAAAAAIdI/IzwM58GKx_w/s1600/death-adder.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://4.bp.blogspot.com/-hJiY55eJhGE/U3h0aXG4wtI/AAAAAAAAIdI/IzwM58GKx_w/s1600/death-adder.jpg" alt="Death Adder" width="400" height="196" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>यह सांप ऑस्ट्रेलिया और न्यू गुइना में पाया जाता है। यह सांप घात लगाकर दूसरे सांपो का शिकार करके खा जाता है। इसका ज़हर न्यूरोटॉक्सिन होता है।  यह एक बार में 100 mg तक ज़हर शिकार के शरीर में छोड़ सकता है। हालांकि यह बहुत विषैला है फिर भी यह इंसानो के लिए इतना खतरनाक नहीं है क्योकि इसके विष का शरीर पर असर बहुत धीरे होता है। इसके विष का पूरी तरह असर होने में 6 घंटे तक लग जाते है। इसलिए एंटी वेनीम इसके इलाज़ में काफी कारगर है, हालांकि एंटी वेनीम की खोज से पहले, इतना धीरे असर होने के बावजूद मरने वालो की संख्या 50 % तक थी।  इसकी एक और विशेषता जो की इसको घातक बनाती है वो है .13 sec के भीतर दुबारा वार करने की क्षमता।</p>
<h5>6. सॉ स्केल्ड वाइपर (Saw Scaled Viper) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://3.bp.blogspot.com/-Wlf2Ra3a-0k/U3h0dADfz-I/AAAAAAAAId0/Q-Pni2sEjXo/s1600/saw-scaled-viper.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://3.bp.blogspot.com/-Wlf2Ra3a-0k/U3h0dADfz-I/AAAAAAAAId0/Q-Pni2sEjXo/s1600/saw-scaled-viper.jpg" alt="Saw Scaled Viper" width="400" height="250" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>वाइपर वैसे तो पुरे संसार में पाए जाते है और इनकी अधिकांश प्रजातिया होती भी ज़हरीली है, लेकिन इनकी सबसे ज़हरीली प्रजाति सॉ स्केल्ड वाइपर और चेन वाइपर भारत, चीन और साउथ ईस्ट एशिया में पाई जाती है।  यही सांप भारत में सांपो के काटने से होने वाली सबसे ज्यादा मौतो के लिए ज़िम्मेदार है। ये सांप प्राय: बारिश के बाद शिकार की तलाश में निकलते हैं और बन जाते हैं इंसानों के दुश्मन। काटने के आधे घंटे के भीतर इंसान खत्म हो जाता है। वाइपर के काटते ही जिस हिस्से में इसने काटा है वहां तेजी से खून बहना शुरू हो जाता है। पूरे बदन में जानलेवा दर्द शुरू हो जाता है। मसूड़ो से खून निकलना शुरू हो जाता है।ब्लडप्रेशर में तेजी से गिरावट आती है आदमी कई बार खून की उल्टियां करता है और नतीजा होता है मौत।</p>
<h5>7. फ़िलिपीनी कोबरा ( Philippine Cobra) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://4.bp.blogspot.com/-X8H-mwaZd4M/U3h0btBDr8I/AAAAAAAAIdY/IdzMy0SiFJs/s1600/philippine-cobra.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://4.bp.blogspot.com/-X8H-mwaZd4M/U3h0btBDr8I/AAAAAAAAIdY/IdzMy0SiFJs/s1600/philippine-cobra.jpg" alt="Philippine Cobra" width="400" height="385" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>कोबरा की अधिकांश प्रजातिया ज्यादा ज़हरीली नहीं होती है पर फ़िलिपीनी कोबरा इसका अपवाद है। इसकी सबसे बड़ी खासियत यह है की यह शिकार को डसने की बजाय उसपर दूर से ज़हर थूकता है। ये 3 मीटर की दुरी से भी शिकार पर ज़हर थूक सकता है। ये एक बार में काफी मात्रा में ज़हर थुकता है। इसका ज़हर न्यूरो टॉक्सिक होता है जो की सीधे श्वसन और हृदय तंत्र पर असर दिखाता है। ज़हर तत्काल अपना असर दिखाना शुरु कर देता है। सांस लेना बेहद मुश्किल हो जाता है नतीजा होता है हर्टअटैक। इसके ज़हर थूकने के आधे घंटे के अंदर शिकार की मौत हो जाती है।</p>
<h5>8. टाइगर स्नेक (Tiger Snake) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://4.bp.blogspot.com/-hJiY55eJhGE/U3h0aXG4wtI/AAAAAAAAIdI/IzwM58GKx_w/s1600/death-adder.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://4.bp.blogspot.com/-hJiY55eJhGE/U3h0aXG4wtI/AAAAAAAAIdI/IzwM58GKx_w/s1600/death-adder.jpg" alt="Tiger Snake" width="400" height="196" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>यह स्नेक ऑस्ट्रेलिया में पाया जाता है।  इसके अंदर बहुत पावरफुल न्यूरो टॉक्सिक ज़हर होता है। इसके काटने के बाद 30 मिनिट से 24 घंटे के अंदर इंसान की मौत हो जाती है। एंटी वेनीन बनने से पूर्व इसके काटने से मरने वाले इंसानो का प्रतिशत 70 था।  इसके बावजूद भी यह इंसानो के लिए ज्यादा खतरनाक नहीं है क्योकि इंसानो से मुठभेड़ होने पर यह भाग जाता है यह काटता उसी स्थिति में है जब यह किसी कोने में हो और भागने की कोई जगह न हो।</p>
<h5>9. ब्लैक माम्बा (Black Mamba) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td style="text-align: center;"><a style="margin-left: auto; margin-right: auto;" href="http://3.bp.blogspot.com/-DL9lAlF06IA/U3h0KqNq2eI/AAAAAAAAIc4/kgBzartWC5M/s1600/black-mamba.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://3.bp.blogspot.com/-DL9lAlF06IA/U3h0KqNq2eI/AAAAAAAAIc4/kgBzartWC5M/s1600/black-mamba.jpg" alt="Black Mamba" width="312" height="400" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>ब्लैक माम्बा तक़रीबन पुरे अफ्रीका में पाया जाता है और यह सांप अफ्रीका में सांप के काटने से होने वाली सबसे ज्यादा मौतों के लिए ज़िम्मेदार है। यह धरती पर सबसे तेज़ चलने वाला सांप है जो कि 20 किलोमीटर प्रतिघंटा की रफ्तार से अपने शिकार का पीछा कर सकता है। खतरा महसूस होने पर ये लगातार 10-12 बार काटता है और 400 मिलीग्राम तक ज़हर इंसान के शरीर में छोड़ देता है। इसका ज़हर फ़ास्ट एक्टिंग न्यूरो टॉक्सिक होता है। बलैक मांबा का सिर्फ 1 मिलीग्राम ज़हर ही इंसान को खत्म करने के लिए काफी है। मांबा के काटते ही आदमी की आंखों के आगे अंधेरा छा जाता है, शरीर के जिस हिस्से पर उसने काटा है वहां, निहायत तेज़ दर्द होता है। काटने के 15 मिनिट से लेकर 3 घण्टे के अंदर इंसान की मौत हो जाती है।  एंटी वेनीन बनने से पूर्व इसका काटा कोई भी इंसान बच नहीं सकता था।  अफ्रीका में ये सांप इतना ज़्यादा पाया जाता है कि अस्पताल पहुंचते ही सबसे पहले इसी सांप का एंटीडोट मरीज को दिया जाता है।</p>
<h5>10. ताइपन (Taipan) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://1.bp.blogspot.com/-dc9l5Nh1p-Y/U3h6VHP0ZXI/AAAAAAAAIeI/XsRAfHKZp4U/s1600/coastaltaipan.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://1.bp.blogspot.com/-dc9l5Nh1p-Y/U3h6VHP0ZXI/AAAAAAAAIeI/XsRAfHKZp4U/s1600/coastaltaipan.jpg" alt="Taipan" width="400" height="263" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>ताइपन आस्ट्रेलिया में पाया जानेवाला दूसरा सबसे खतरनाक सांप। ये एक बार में इतना ज़्यादा ज़हर छोड़ता है कि उससे एक बार में 12,000 पिग की जान जा सकती है। इसका ज़हर भी न्यूरो टॉक्सिक होता है। अफ्रीकन ब्लैक माम्बा की तरह एंटी वेनीन बनने से पूर्व इसका काटा कोई भी इंसान बच नहीं पाता था। इसके काटने के एक घंटे के अंदर इंसान की मौत हो जाती है।</p>
<h5>11. ब्लू करैत (Blue Krait) :</h5>
<table class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;" cellspacing="0" cellpadding="0"><tbody><tr><td style="text-align: center;"><a style="clear: left; margin-bottom: 1em; margin-left: auto; margin-right: auto;" href="http://1.bp.blogspot.com/-sNeyoATjymw/U3h0aZ0IJGI/AAAAAAAAIdc/AisMsMl8x4k/s1600/blue-krait.jpg"><img class="alignnone" title="Top 10 Most Venomous Snake Information in Hindi" src="http://1.bp.blogspot.com/-sNeyoATjymw/U3h0aZ0IJGI/AAAAAAAAIdc/AisMsMl8x4k/s1600/blue-krait.jpg" alt="Blue Krait" width="400" height="256" border="0"></a></td>
</tr><tr>
</tr></tbody></table><p></br></br>ये सांप साउथ ईस्ट एशिया और इंडोनेशिया में पाया जाता है। ये सांप भी डेथ एडर की तरह दूसरे सांपो का शिकार करके खाता है। ये सांप सामान्यत: रात के वक्त शिकार ढूंढने निकलते हैं। काफी ज़हरीले होते हैं पर साथ ही निहायत डरपोक भी। इंसानी बस्तियों से दूर रहते हैं और उलझना पसंद नहीं करते। लेकिन एक बार यदि इन्हें अंदेशा हो जाए कि बिना उलझे काम नहीं चलेगा तो फिर ये छोड़ते भी नहीं। इनके काटने के तुरंत बाद आदमी को लकवा मार जाता है। इनका ज़हर भी न्यूरो टॉक्सिक होता है। एंटी वेनीन बनने से पूर्व इसके काटने से मरने वालो की संख्या 85 % थी।</p>
</p>
</div></div></div></div>
';
ob_end_flush();
?>